# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
#
# FanGate 2 Localhost App
# FanGate 2 Public App

development:
 FACEBOOK_KEY: "383808351735443"
 FACEBOOK_SECRET: fea525a41da25046f17a771e52eaf248
production:
 FACEBOOK_KEY: "371897399581991"
 FACEBOOK_SECRET: a2e71fa2f0fb65270326f7e21b0b8050